### ISSUE TITLE
Re-inclusion request

### ISSUE THREAD

**Issue by keiviv** [luapower/wluajit#1]
Hi, @capr

Cosmin — huge thanks for Luapower, it's absolutely the best Lua distribution. It's surely the most flexible one — can use binaries, can build.

I'm one of those who use it just for the binaries, and hence a question — if it's totally against your vision to re-include wluajit into the main branch?

Yes, it is functionally superseded by bundle, but those who only need this tiny but useful binary must have the full build toolchain just for it. Would it be too much technical trouble to re-include this — if, again, it's not against your conceptual vision of the project?

P.S. There is a small typo in wluajit/csrc/wluajit/luajit.rc:13: copmiler > compiler. I only noticed it because made the same exact typo an hour ago :)

**Comment by capr** [comment]
Hi,

You can add wluajit to your luapower folder with `mgit clone luapower/wluajit` or if you use the big zip from the homepage just download it and dump it in your luapower folder.

Hope this helps.

**Comment by keiviv** [comment]
It is not possible — as you removed it from the main build (hence the re-inclusion request). The latest wluajit binary is built against luajit 2.1.0-alpha1, so it is not compatible with the current build either — as it's beta3 already.

You can see there is no wluajit in [the master bin](https://github.com/luapower/luapower-all/tree/master/bin/mingw64).

I really hope you can include it back, if it's not a huge problem to build this tiny but useful binary.

**Comment by keiviv** [comment]
Yay thank you, Cosmin! Tested the newly built wluajit against the master luajit, all works fine.
You're a rockstar <3
I've tried every other Lua distribs, including Luarocks, ULua, LuaDist, LuaForWin... nothing comes close to you. And your mgit tool is something!

**Comment by capr** [comment]
Thanks! Glad I could help.
